### ISSUE TITLE
Size of image referenced by og:image

### ISSUE THREAD

**Issue by torenord** [willnorris/wordpress-opengraph#24]
I have a problem with images referenced by `og:image` not being big enough to be acceptable to Facebook. Following is the warning I see in Facebook's Open Graph Object Debugger:

> og:image was not defined, could not be downloaded or was not big enough. Please define a chosen image using the og:image metatag, and use an image that's at least 200x200px and is accessible from Facebook.

Below is my workaround. Is there a reason why the size is `medium` and not `full`?.

```
--- A/wp-content/plugins/opengraph/opengraph.php
+++ b/wp-content/plugins/opengraph/opengraph.php
@@ -229,7 +229,7 @@ function opengraph_default_image( $image ) {
                // get URLs for each image
                $image = array();
                foreach ( $image_ids as $id ) {
-                       $thumbnail = wp_get_attachment_image_src( $id, 'medium' );
+                       $thumbnail = wp_get_attachment_image_src( $id, 'full' );
                        if ( $thumbnail ) {
                                $image[] = $thumbnail[0];
                        }
```

**Comment by willnorris** [comment]
certainly no good reason I can think of.  I apparently added that in ac20c504fa62bc2cc49a4ba393d93dbd62fcfef2 and it's been the same ever since.  Maybe Facebook didn't display the nice big images back in 2012?  The browser isn't downloading this image, so there's certainly no reason not to put the full size image here.

@pfefferle, what do you think?

**Comment by pfefferle** [comment]
Full size sounds good! Can you send a pull request for your change @torenord ?
